### ISSUE TITLE
Fixing portals of other mods

### ISSUE THREAD

**Issue by SimonMeskens** [blay09/NetherPortalFix#25]
This is more of a feature request. Can we potentially make it so you can set up the parameters per dimension combination in the config? There are a few mods like Aether Legacy and Betweenlands that face similar issues to vanilla portals and the code looks to be generic enough to cover whatever dimension hop necessary.

**Comment by BlayTheNinth** [comment]
I can try it at some point, but it would be very experimental and possibly unstable, since the other mods might not be able to handle it as well as vanilla did (I'm thinking of things such as custom teleport handling etc.). 
But it might be okay as an option that people would actively have to put effort into enabling (that way they can't blame me if all goes wrong).

**Comment by SimonMeskens** [comment]
Sounds good. I have to fix this for my modpack anyway, so I'll do the due diligence for you and let you know how well it works for the mods I'm using.
