### ISSUE TITLE
Injury going out of a portal

### ISSUE THREAD

**Issue by PernDragon** [blay09/NetherPortalFix#46]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.66

### Mod Version

9.0.0

### Describe the Issue

I enter a portal to the Nether or Return and Sustain some injury on the exit.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine

**Comment by kirjorjos** [comment]
Same thing happening to me in 1.16.5, didn't think much of it until I died and my (quark oddities) grave didn't spawn as far as I can tell.

**Comment by BlayTheNinth** [comment]
While in older versions (prior to Minecraft 1.17) NetherPortalFix may have been responsible in giving players suffocation damage due to teleporting the player's head into the portal frame, newer versions completely leave the portal identification and teleportation up to Vanilla. There is nothing that NetherPortalFix could be doing anymore to cause injury.

However, there are many reports of injury on teleportation happening in Vanilla Minecraft, for example on slow servers.
See https://bugs.mojang.com/browse/MCPE-28765 and the many linked duplicate issues over there.
